apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildbuddy.name" . }}
{{- if or .Values.service.annotations .Values.iapIngress.enabled}}
  annotations:
{{- if .Values.iapIngress.enabled }}
    beta.cloud.google.com/backend-config: '{ "ports": { "grpc": "{{ include "buildbuddy.fullname" . }}-grpc-backend-config", "grpcs": "{{ include "buildbuddy.fullname" . }}-grpc-backend-config", "http": "{{ include "buildbuddy.fullname" . }}-http-backend-config", "https": "{{ include "buildbuddy.fullname" . }}-http-backend-config"} }'
    cloud.google.com/app-protocols: '{"grpc":"HTTP2", "grpcs":"HTTP2"}'
{{- end }}
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: 'TCP'
      port: {{ .Values.service.externalHTTPPort }}
      targetPort: {{ .Values.service.internalHTTPPort }}
    - name: grpc
      protocol: 'TCP'
      port: {{ .Values.service.externalGRPCPort }}
      targetPort: {{ .Values.service.internalGRPCPort }}
    {{ if and .Values.service.externalHTTPSPort .Values.service.internalHTTPSPort }}
    - name: https
      protocol: 'TCP'
      port: {{ .Values.service.externalHTTPSPort }}
      targetPort: {{ .Values.service.internalHTTPSPort }}
    {{ end }}
    {{ if and .Values.service.externalGRPCSPort .Values.service.internalGRPCSPort }}
    - name: grpcs
      protocol: 'TCP'
      port: {{ .Values.service.externalGRPCSPort }}
      targetPort: {{ .Values.service.internalGRPCSPort }}
    {{ end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}